-- CreateEnum
CREATE TYPE "PipelineStatus" AS ENUM ('INTERESSENT', 'SETTING_TERMINIERT', 'SETTING_NOSHOW', 'DOWNSELL', 'CLOSING_TERMINIERT', 'CLOSING_NOSHOW', 'KUNDE', 'LOST');

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "status" "PipelineStatus" NOT NULL DEFAULT 'INTERESSENT';
